# Generated by Django 2.2 on 2020-02-02 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('type', models.CharField(choices=[('Customer', 'Customer'), ('Company', 'Company'), ('Vendor', 'Vendor')], max_length=32)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Cash', 'Cash'), ('Others', 'Others')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
    ]
