# Generated by Django 2.2 on 2020-02-02 12:20

import SM.dayBook
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0002_daybook'),
    ]

    operations = [
        migrations.AddField(
            model_name='daybook',
            name='number',
            field=models.CharField(default=SM.dayBook.random_string, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
