# Generated by Django 2.2.7 on 2020-02-04 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SM', '0004_auto_20200202_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('unit_price', models.CharField(max_length=100, null=True)),
                ('u_o_m', models.CharField(max_length=100, null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('product_type', models.CharField(max_length=100, null=True)),
                ('purchase_rate', models.CharField(max_length=100, null=True)),
                ('purchase_rate_currency', models.CharField(max_length=100, null=True)),
                ('h_s_n_or_s_a_c', models.CharField(max_length=100, null=True)),
                ('s_k_u', models.CharField(max_length=100, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('c_e_s_s_percent', models.CharField(max_length=100, null=True)),
                ('c_e_s_s', models.CharField(max_length=100, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_sm_product_related', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_sm_product_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
