# Generated by Django 2.2 on 2020-02-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0004_auto_20200202_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Employ', 'Employ'), ('Vendor', 'Vendor')], max_length=32),
        ),
    ]
