# Generated by Django 2.2 on 2020-02-04 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SM', '0005_auto_20200202_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('PIN_code', models.CharField(blank=True, max_length=100, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('GSTIN', models.CharField(blank=True, max_length=100, null=True)),
                ('Taxation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_inclusive', models.CharField(blank=True, max_length=100, null=True)),
                ('TIN', models.CharField(blank=True, max_length=100, null=True)),
                ('VAT', models.CharField(blank=True, max_length=100, null=True)),
                ('service_tax_no', models.CharField(blank=True, max_length=100, null=True)),
                ('CST_tin_no', models.CharField(blank=True, max_length=100, null=True)),
                ('PAN', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_details', models.TextField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_sm_companydetail_related', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_sm_companydetail_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
