# Generated by Django 2.2.7 on 2020-02-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0006_auto_20200204_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
