# Generated by Django 2.2.7 on 2020-02-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0007_auto_20200204_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiryform',
            old_name='contact_No',
            new_name='contact_no',
        ),
        migrations.RenameField(
            model_name='enquiryform',
            old_name='customerType',
            new_name='customer_type',
        ),
        migrations.RenameField(
            model_name='enquiryform',
            old_name='email_Id',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='enquiryform',
            old_name='enquiryDate',
            new_name='enquiry_date',
        ),
        migrations.RenameField(
            model_name='enquiryform',
            old_name='enquiryType',
            new_name='enquiry_type',
        ),
        migrations.RenameField(
            model_name='enquiryform',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='enquiryform',
            old_name='handledBy',
            new_name='handled_by',
        ),
        migrations.RenameField(
            model_name='enquiryform',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='enquiryform',
            old_name='mobile_No',
            new_name='mobile_no',
        ),
        migrations.RenameField(
            model_name='enquiryform',
            old_name='enquiry_Name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='enquiryform',
            old_name='whatsUP_No',
            new_name='whatsapp_no',
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
