# Generated by Django 2.2 on 2020-02-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0007_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='PIN_code',
            new_name='PIN_Code',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='billing_address',
            new_name='billing_Address',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='contact_name',
            new_name='contact_Name',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='other_vendor_details',
            new_name='other_Vendor_Details',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='private_vendor_details',
            new_name='private_Vendor_Details',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_code',
            new_name='vendor_Code',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_name',
            new_name='vendor_Name',
        ),
    ]
