# Generated by Django 2.2 on 2020-02-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0008_auto_20200204_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetail',
            old_name='CST_tin_no',
            new_name='CST_Tin_No',
        ),
        migrations.RenameField(
            model_name='companydetail',
            old_name='PIN_code',
            new_name='PIN_Code',
        ),
        migrations.RenameField(
            model_name='companydetail',
            old_name='Taxation_type',
            new_name='Taxation_Type',
        ),
        migrations.RenameField(
            model_name='companydetail',
            old_name='additional_details',
            new_name='additional_Details',
        ),
        migrations.RenameField(
            model_name='companydetail',
            old_name='company_name',
            new_name='company_Name',
        ),
        migrations.RenameField(
            model_name='companydetail',
            old_name='company_phone',
            new_name='company_Phone',
        ),
        migrations.RenameField(
            model_name='companydetail',
            old_name='service_tax_no',
            new_name='service_Tax_No',
        ),
        migrations.RenameField(
            model_name='companydetail',
            old_name='tax_inclusive',
            new_name='tax_Inclusive',
        ),
    ]
