# Generated by Django 2.2.7 on 2020-02-04 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SM', '0008_auto_20200204_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('v_a_t_no', models.CharField(max_length=100, null=True)),
                ('invoice_no', models.CharField(max_length=100, null=True)),
                ('p_o_number', models.CharField(max_length=100, null=True)),
                ('p_o_date', models.CharField(max_length=100, null=True)),
                ('issue_date', models.CharField(max_length=100, null=True)),
                ('due_date', models.CharField(max_length=100, null=True)),
                ('amount_before_tax', models.CharField(max_length=100, null=True)),
                ('discount', models.CharField(max_length=100, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('total', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('amount_paid', models.CharField(max_length=100, null=True)),
                ('balance', models.CharField(max_length=100, null=True)),
                ('dr_cr', models.CharField(max_length=100, null=True)),
                ('date_of_payment', models.CharField(max_length=100, null=True)),
                ('invoice_type', models.CharField(max_length=100, null=True)),
                ('private_note', models.TextField(null=True)),
                ('payments', models.TextField(null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_sm_invoice_related', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_sm_invoice_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
