# Generated by Django 2.2.7 on 2020-02-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0009_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='dr_cr',
            new_name='dr_or_cr',
        ),
    ]
