# Generated by Django 2.2 on 2020-02-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0011_auto_20200204_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='balance',
            new_name='PIN_Code',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='billing_City',
            new_name='TIN',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='billing_Country',
            new_name='VAT_no',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='billing_State',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='billing_Zip',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_TIN',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='private_Details',
            new_name='other_Client_Details',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='shipping_Address',
            new_name='private_Client_Details',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='shipping_City',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='shipping_Country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='shipping_State',
        ),
        migrations.RemoveField(
            model_name='client',
            name='shipping_Zip',
        ),
    ]
