# Generated by Django 2.2 on 2020-02-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0012_auto_20200204_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tax',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='tax(%)'),
        ),
    ]
