# Generated by Django 2.2 on 2020-02-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0013_client_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tax',
        ),
    ]
