# Generated by Django 2.2 on 2020-02-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0014_remove_client_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='PIN_Code',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='VAT_no',
            new_name='billing_City',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='city',
            new_name='billing_Country',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_Name',
            new_name='billing_State',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='country',
            new_name='billing_Zip',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='currency',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='other_Client_Details',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='private_Client_Details',
            new_name='shipping_Address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='state',
            new_name='shipping_City',
        ),
        migrations.AddField(
            model_name='client',
            name='shipping_Country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='shipping_State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='shipping_Zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='billing_Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
