# Generated by Django 2.2 on 2020-02-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0015_auto_20200204_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='PAN',
            new_name='billing_City',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='PIN_Code',
            new_name='billing_Country',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='VAT_no',
            new_name='billing_State',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='city',
            new_name='billing_Zip',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='country',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='currency',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='other_Vendor_Details',
            new_name='shipping_Address',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='private_Vendor_Details',
            new_name='shipping_City',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='state',
            new_name='shipping_Country',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_Code',
            new_name='shipping_State',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_Name',
            new_name='shipping_Zip',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='billing_Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
