# Generated by Django 2.2 on 2020-02-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0018_auto_20200204_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryform',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
