# Generated by Django 2.2 on 2020-02-04 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SM', '0019_enquiryform_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('GSTIN', models.CharField(max_length=100, null=True)),
                ('purchase_Order_No', models.CharField(max_length=100, null=True)),
                ('PO_Number', models.CharField(max_length=100, null=True)),
                ('issue_Date', models.CharField(max_length=100, null=True)),
                ('valid_Until', models.CharField(max_length=100, null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('CGST', models.CharField(max_length=100, null=True)),
                ('SGST', models.CharField(max_length=100, null=True)),
                ('IGST', models.CharField(max_length=100, null=True)),
                ('CESS', models.CharField(max_length=100, null=True)),
                ('total', models.CharField(max_length=100, null=True)),
                ('billed', models.CharField(max_length=100, null=True)),
                ('advanced_Payments', models.CharField(max_length=100, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_sm_purchaseorder_related', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_sm_purchaseorder_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
