# Generated by Django 2.2 on 2020-02-02 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostumerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiryType', models.CharField(blank=True, max_length=100, null=True)),
                ('enquiryFor', models.CharField(max_length=100, null=True)),
                ('startPrice', models.CharField(blank=True, max_length=100, null=True)),
                ('endPrice', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('enquiryDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('handledBy', models.CharField(max_length=100, null=True)),
                ('mobile_No', models.CharField(max_length=100, null=True)),
                ('whatsUP_No', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_No', models.CharField(blank=True, max_length=100, null=True)),
                ('email_Id', models.CharField(blank=True, max_length=100, null=True)),
                ('customerType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EnquiryForm.CostumerType')),
                ('enquiryType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EnquiryForm.EnquiryType')),
            ],
        ),
    ]
