# Generated by Django 2.2 on 2020-02-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquiryForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirytype',
            name='enquiryFor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
