# Generated by Django 2.2 on 2020-02-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquiryForm', '0003_auto_20200202_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiryform',
            name='enquiryFor',
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='enquiry_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquirytype',
            name='enquiryType',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
